# Default values for rook-gitlab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# the region is used by s3
rook:
  region: &region us-east-1
  s3config: &s3config gitlab-s3-config-map #change to configmap from 
  user: &rook-user gitlab-s3-user

# anchor notes: https://yaml.org/spec/1.2/spec.html

# TODO replace $BUCKET_SECRET with yaml anchors https://confluence.atlassian.com/bitbucket/yaml-anchors-960154027.html

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

securityContext: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


tolerations: []

affinity: {}

gitlab:
    
  
  # aws_host: setBy_install.sh
  # aws_access_key_id: setBy_install.sh
  # aws_secret_access_key: setBy_install.sh

  ## Automatic shared secret generation
  ## doc/installation/secrets.md
  ## doc/charts/shared-secrets
  shared-secrets:
    enabled: true
    rbac:
      create: true
  
  # TODO specify secrets for the below sections
  # https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/doc/charts/globals.md#connection
  gitlab:
    unicorn: &init_cont
      s3config: *s3config
        ## Init containers configure gitlab's s3 credentials by altering these files in the pods. 
        # 1. backups are in `~/.s3cfg` @ see https://s3tools.org/kb/item14.htm
        # 2. appConfig bucket storage is in `` @ see
      ## more references
        # useful gitlab issue https://gitlab.com/gitlab-org/charts/gitlab/issues/1920
        # 
      extraInitContainers: |
        - name: secret-parser
          image: busybox:1.28
          command: ['echo', '$S3_CONFIG', '|', 'envsubst', '|', '/etc/gitlab/objectstorage/ {{- .Chart.Name }}' ]
          env:
          - name: ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: secretname #user secret name
                key: accesskey-key #accesskey?
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: secretname #user secret name
                key: secretkey-key #secretkey?
          - name: AWS_HOST
            valueFrom:
              secretKeyRef:
                name: secretname #user secret name
                key: host-key #user host key
          - name: S3_CONFIG
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.s3config }}
                key: connection
    gitaly:
      <<: *init_cont

    gitlab-shell:
      <<: *init_cont
    
    mailroom:
      <<: *init_cont
    
    migrations:
      <<: *init_cont
    
    sidekiq:
      <<: *init_cont
    
    task-runner:
      <<: *init_cont
    
        # TODO specify secrets for the below sections
  # https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/doc/charts/globals.md#connection
  gitlab:
    unicorn: &init_cont
      s3config: *s3config
      user: *rook-user
        ## Init containers configure gitlab's s3 credentials by altering these files in the pods with keys from the ceph user
        # 1. backups are in `~/.s3cfg` @ see https://s3tools.org/kb/item14.htm
        # 2. appConfig bucket storage is in `/etc/gitlab/objectstorage/*` @ see https://gitlab.com/gitlab-org/charts/gitlab/issues/1920
      ## more references
        # gitlab issue https://gitlab.com/gitlab-org/charts/gitlab/issues/1920
        # rook docs: https://rook.io/docs/rook/v1.2/ceph-object.html
      extraInitContainers: |
        - name: secret-parser
          image: busybox:1.28
          command: ['echo', '$S3_CONFIG', '|', 'envsubst', '|', "tee", '/etc/gitlab/objectstorage/artifacts', '/etc/gitlab/objectstorage/lfs', "/etc/gitlab/objectstorage/uploads", "/etc/gitlab/objectstorage/packages", "/etc/gitlab/objectstorage/external_diffs" ]
          env:
          - name: ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: secretname #user secret name
                key: AccessKey #accesskey?
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-object-user-%s-store-%s" .Release.Namespace .Release.Name .Values.user }}
                key: SecretKey 
          - name: AWS_HOST
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-object-user-%s-store-%s" .Release.Namespace .Release.Name .Values.user }}
                key: host-key #user host key
          - name: S3_CONFIG
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.s3config }}
                key: connection
    gitaly:
      <<: *init_cont

    gitlab-shell:
      <<: *init_cont
    
    mailroom:
      <<: *init_cont
    
    migrations:
      <<: *init_cont
    
    sidekiq:
      <<: *init_cont
    
    task-runner:
      <<: *init_cont
    
  registry:
    storage:
      secret: registry-storage
      key: config
  
  global:
    registry:
      bucket: gitlab-registry-storage
    hosts:
      https: false
    
    edition: ce
    ingress:
      configureCertmanager: false
      enabled: false
      tls:
        enabled: false
        
        
    mino:
      # https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/doc/charts/globals.md#configure-minio-settings
      enabled: false

    ## Installation & configuration of gitlab/gitlab-runner
    ## See requirements.yaml for current version
    gitlab-runner:
      install: true
    
    operator:
      enabled: false
      rollout:
        # Enables automatic pause for deployment rollout. This must be set to `true` to fix
        # Helm's issue with 3-way merge. See:
        #   https://gitlab.com/gitlab-org/charts/gitlab/issues/1262
        #   https://github.com/helm/helm/issues/3805
        autoPause: true

    runners:
      locked: false
      cache:
        cacheType: s3
        s3BucketName: runner-cache
        cacheShared: true
        s3BucketLocation: *region
        s3CachePath: gitlab-runner
        s3CacheInsecure: false
        ## GitLab operator is Alpha. Not for production use.
    



  ###################################STORAGE STUFF###############################

  # according to this https://gitlab.com/gitlab-org/charts/gitlab/-/tree/master/doc/advanced/external-object-storage
  # each storage type needs its own bucket, but they can share a secret.
  # so you can probably use a shared user for all the buckets

  ## object storage settings for future: https://docs.gitlab.com/ee/administration/job_artifacts.html#s3-compatible-connection-settings

      ## doc/charts/globals.md#lfs-artifacts-uploads-packages-external-mr-diffs
      ## example storage settings: https://gitlab.com/gitlab-org/charts/gitlab/blob/master/examples/values-external-objectstorage.yaml
    appConfig:

      # https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/doc/charts/globals.md#configure-appconfig-settings
      lfs: &storage-anchor
        # https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/doc/charts/globals.md#lfs-artifacts-uploads-packages-and-external-mr-diffs
        enabled: true
        proxy_download: true
        bucket: git-lfs
        connection: 
          # https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/doc/charts/globals.md#connection
          secret: *bucket_secret
          key: connection
          

      # the following configurations should be overriden without the user caring, but I'm putting them here for now    

      artifacts:
        <<: *storage-anchor
        bucket: gitlab-artifacts

      uploads:
        <<: *storage-anchor
        bucket: gitlab-uploads
        
      packages:
        <<: *storage-anchor
        bucket: gitlab-packages
        
      externalDiffs:
        when:
        <<: *storage-anchor
        bucket: gitlab-mr-diffs

      ## doc/charts/globals.md#pseudonymizer-settings
      pseudonymizer:
        # https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/doc/charts/globals.md#pseudonymizer-settings
        configMap:
        <<: *storage-anchor
        bucket: gitlab-pseudo
          # key:
      
      backups:
        # <<: *storage-anchor
        bucket: gitlab-backups
        tmpBucket: tmp
      
      omniauth:
      #https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/doc/charts/globals.md#omniauth
        enabled: false

    
