# Default values for rook-gitlab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# the region is used by s3
region: us-east-1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


tolerations: []

affinity: {}

gitlab:
  ## Automatic shared secret generation
  ## doc/installation/secrets.md
  ## doc/charts/shared-secrets
  shared-secrets:
    enabled: true
    rbac:
      create: true

  ## Installation & configuration of gitlab/gitlab-runner
  ## See requirements.yaml for current version
  gitlab-runner:
    install: true
  
  runners:
    locked: false
    cache:
      cacheType: s3
      s3BucketName: runner-cache
      cacheShared: true
      s3BucketLocation: us-east-1
      s3CachePath: gitlab-runner
      s3CacheInsecure: false

  global:
      ## GitLab operator is Alpha. Not for production use.
    operator:
      enabled: false
      rollout:
        # Enables automatic pause for deployment rollout. This must be set to `true` to fix
        # Helm's issue with 3-way merge. See:
        #   https://gitlab.com/gitlab-org/charts/gitlab/issues/1262
        #   https://github.com/helm/helm/issues/3805
        autoPause: true

    edition: ce
    ingress:
      configureCertmanager: false
      # tls:
      #   enabled: false
    mino:
      enabled: false

###################################STORAGE STUFF###############################

# according to this https://gitlab.com/gitlab-org/charts/gitlab/-/tree/master/doc/advanced/external-object-storage
# each storage type needs its own bucket, but they can share a secret.
# so you can probably use a shared user for all the buckets

## object storage settings for future: https://docs.gitlab.com/ee/administration/job_artifacts.html#s3-compatible-connection-settings

    ## doc/charts/globals.md#lfs-artifacts-uploads-packages-external-mr-diffs
    ## example storage settings: https://gitlab.com/gitlab-org/charts/gitlab/blob/master/examples/values-external-objectstorage.yaml
    lfs:
      enabled: false
      proxy_download: true
      bucket: git-lfs
      connection: {}
        # secret:
        # key:

# the following configurations should be overriden without the user caring, but I'm putting them here for now    


    artifacts:
      enabled: true
      proxy_download: true
      bucket: gitlab-artifacts
      connection: {}
        # secret:
        # key:
    uploads:
      enabled: true
      proxy_download: true
      bucket: gitlab-uploads
      connection: {}
        # secret:
        # key:
    packages:
      enabled: true
      proxy_download: true
      bucket: gitlab-packages
      connection: {}
    externalDiffs:
      when:
      proxy_download: true
      bucket: gitlab-mr-diffs
      connection: {}

    ## doc/charts/globals.md#pseudonymizer-settings
    pseudonymizer:
      configMap:
      bucket: gitlab-pseudo
      connection: {}
        # secret:
        # key:
    backups:
      bucket: gitlab-backups
      tmpBucket: tmp


