apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name }}-s3-storage-class
  annotations:
    "helm.sh/hook": pre-install
    #https://helm.sh/docs/topics/charts_hooks/
provisioner: ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: {{ .Release.Name }}-store
  objectStoreNamespace: {{ .Release.Namespace }}
  region: {{ .Values.rook.region }}
